BEGIN;

CREATE SCHEMA IF NOT EXISTS auth_db AUTHORIZATION CURRENT_USER;
CREATE SCHEMA IF NOT EXISTS patient_db AUTHORIZATION CURRENT_USER;
CREATE SCHEMA IF NOT EXISTS solicitud_db AUTHORIZATION CURRENT_USER;
CREATE SCHEMA IF NOT EXISTS monitoring_db AUTHORIZATION CURRENT_USER;
CREATE SCHEMA IF NOT EXISTS evaluacion_db AUTHORIZATION CURRENT_USER;
CREATE SCHEMA IF NOT EXISTS teleconsult_db AUTHORIZATION CURRENT_USER;
CREATE SCHEMA IF NOT EXISTS emergency_db AUTHORIZATION CURRENT_USER;
CREATE SCHEMA IF NOT EXISTS cierre_db AUTHORIZATION CURRENT_USER;
CREATE SCHEMA IF NOT EXISTS historial_db AUTHORIZATION CURRENT_USER;
CREATE SCHEMA IF NOT EXISTS audit_db AUTHORIZATION CURRENT_USER;
CREATE SCHEMA IF NOT EXISTS admin_db AUTHORIZATION CURRENT_USER;

COMMIT;
